import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    // Get user from auth header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Authorization required' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const token = authHeader.replace('Bearer ', '');
    
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: 'Invalid token' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const userId = user.id;

    // Collect all user data
    const exportData: Record<string, unknown> = {
      export_date: new Date().toISOString(),
      user_id: userId,
      email: user.email,
    };

    // Get profile data
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', userId)
      .single();
    exportData.profile = profile || null;

    // Get user roles
    const { data: roles } = await supabase
      .from('user_roles')
      .select('role, created_at')
      .eq('user_id', userId);
    exportData.roles = roles || [];

    // Get notifications
    const { data: notifications } = await supabase
      .from('notifications')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });
    exportData.notifications = notifications || [];

    // Get access logs (with anonymized IPs for old records)
    const { data: accessLogs } = await supabase
      .from('access_logs')
      .select('*')
      .eq('user_id', userId)
      .order('timestamp', { ascending: false });
    exportData.access_logs = accessLogs || [];

    // Get alert history
    const { data: alertHistory } = await supabase
      .from('alert_history')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });
    exportData.alert_history = alertHistory || [];

    // Get security audit log entries for this user
    const { data: auditLogs } = await supabase
      .from('security_audit_log')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });
    exportData.security_audit_log = auditLogs || [];

    // Get incidents created by user
    const { data: incidents } = await supabase
      .from('incidents')
      .select('*')
      .or(`created_by.eq.${userId},assigned_to.eq.${userId}`)
      .order('created_at', { ascending: false });
    exportData.incidents = incidents || [];

    // Get compliance reports generated by user
    const { data: complianceReports } = await supabase
      .from('compliance_reports')
      .select('*')
      .eq('generated_by', userId)
      .order('created_at', { ascending: false });
    exportData.compliance_reports = complianceReports || [];

    // Get GDPR export request history
    const { data: exportHistory } = await supabase
      .from('gdpr_export_requests')
      .select('id, status, requested_at, completed_at')
      .eq('user_id', userId)
      .order('requested_at', { ascending: false });
    exportData.previous_export_requests = exportHistory || [];

    // Create GDPR export request record
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 7); // Export expires in 7 days

    await supabase
      .from('gdpr_export_requests')
      .insert({
        user_id: userId,
        status: 'completed',
        export_data: exportData,
        completed_at: new Date().toISOString(),
        expires_at: expiresAt.toISOString(),
      });

    // Return the export data
    return new Response(
      JSON.stringify({
        success: true,
        data: exportData,
        message: 'Your personal data export is ready',
        expires_at: expiresAt.toISOString(),
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Unknown error';
    console.error('Error in gdpr-export:', err);
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});